version: '3.9'

services:
  taskhub.web:
    container_name: taskhub.web
    build:
      context: ./frontend/TaskHub.Web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/TaskHub.Web:/app
      - /app/node_modules
    depends_on:
      - taskhub.api
    command: npm run start
    networks:
      - taskhub-net
  taskhub.api:
    container_name: taskhub.api
    build:
      context: ./backend/TaskHub.WebApi/
      dockerfile: TaskHub.WebApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=taskhub.db;Database=taskhub;User=sa;Password=root@1234;Encrypt=False;
    depends_on:
      - taskhub.db
    networks:
      - taskhub-net
  taskhub.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskhub.db
    environment:
      - MSSQL_SA_PASSWORD=root@1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - taskhub-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  sqlserverdata:
  grafana-storage:


networks:
  taskhub-net:
    driver: bridge
