version: '3.9'

services:
  taskhub.api:
    container_name: taskhub.api
    build:
      context: ./backend/TaskHub.WebApi/
      dockerfile: TaskHub.WebApi/Dockerfile
    ports:
      - "8080:80"   
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=taskhub.db;Database=taskhub;User=sa;Password=root@1234;Encrypt=False;
    depends_on:
      - taskhub.db
  taskhub.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskhub.db
    environment:
      - MSSQL_SA_PASSWORD=root@1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: